routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UrlController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\UrlChecksController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [PageController::class, 'main'])->name('main');
Route::resource('urls', UrlController::class);
Route::resource('urls.checks', UrlChecksController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Url;

class PageController extends Controller
{
    public function main(): object
    {
        return view('main');
    }
}

app/Http/Controllers/UrlChecksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Http;
use DiDom\Document;
use Illuminate\Http\Client\RequestException;
use Illuminate\Http\Client\ConnectionException;

class UrlChecksController extends Controller
{
    public function store(int $id): object
    {
        $url = DB::table('urls')->find($id);
        abort_unless($url, 404);
        try {
            $response = Http::get($url->name);
            $document = new Document($response->body());
            $h1 = optional($document->first('h1'))->text();
            $keywords = optional($document->first('meta[name=keywords]'))->getAttribute('content');
            $description = optional($document->first('meta[name=description]'))->getAttribute('content');
            DB::table('url_checks')->insert([
                'url_id' => $id,
                'status_code' => $response->status(),
                'h1' => $h1,
                'keywords' => $keywords,
                'description' => $description,
                'created_at' => $url->created_at,
                'updated_at' => Carbon::now()
            ]);
            DB::table('urls')->where('id', $id)->update(
                ['updated_at' => Carbon::now()]
            );
            flash('Сайт проанализирован!')->warning();
            return redirect()->route('urls.show', $id);
        } catch (RequestException | ConnectionException $e) {
            flash("Error: {$e->getMessage()}")->error();
        }
        return redirect()->route('urls.show', $id);
    }
}

app/Http/Controllers/UrlController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Validator;

class UrlController extends Controller
{
    public function index(): object
    {
        $urls = DB::table('urls')->orderBy('id', 'asc')->get();
        $checks = DB::table('url_checks')->orderBy('url_id', 'asc')->orderBy('created_at', 'desc')->distinct('url_id')->get();
        $lastCheck = $checks->keyBy('url_id');
        return view('urls.index', compact('urls', 'lastCheck'));
    }
    public function show(int $id): object
    {
        $url = DB::table('urls')->find($id);
        $cheks = DB::table('url_checks')->where('url_id', '=', $id)->orderBy('updated_at', 'desc')->get();
        return view('urls.show', compact('url', 'cheks'));
    }
    public function store(Request $request): object
    {
        $formData = $request->input('url');
        $validator = Validator::make($formData, [
            'name' => 'required|url|max:255'
        ]);
        if ($validator->fails()) {
            flash('Не корректный адрес сайта!')->error();
            return redirect()->route('main');
        }

        $urlData = parse_url($formData['name']);
        $host = "{$urlData['scheme']}://{$urlData['host']}";

        $url = DB::table('urls')->where('name', $host)->first();
        if (! is_null($url)) {
            flash("Такой сайт \"{$url->name}\" уже существует!")->warning();
            $id = $url->id;
        } else {
            $id = DB::table('urls')->insertGetId([
                'name' => $host,
                'created_at' => Carbon::now()
            ]);
            flash('Сайт успешно добавлен!')->success();
        }
        return redirect()->route('urls.show', $id);
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">

    <title>@yield('title')</title>
</head>

<body>
    <div class="wrapper">
        <div class="content">
            <header>
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="{{ route('main') }}">Анализатор страниц</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" href="{{ route('main') }}">Главная</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('urls.index') }}">Сайты</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                @include('flash::message')
            </header>
            <main>
                 @yield('content')
            </main>
        </div>

        <footer class="border-top py-3 mt-5">
            <div class="container-lg">
                <div class="text-center">
                    <p>Drumsid</p>
                </div>
            </div>
        </footer>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
</body>

</html>

resources/views/main.blade.php
@extends('layouts.app')

@section('title', 'Главная')

@section('content')

    <div class="container-fluid bg-dark pt-5 pb-5">
        <div class="container-lg">
            <div class="row">
                <div class="col-12 col-md-10 col-lg-8 mx-auto text-white">
                    <h1 class="display-3 fs-1">Анализатор страниц</h1>
                    <p class="lead fs-5">Бесплатно проверяйте сайты на SEO пригодность</p>
                    {{Form::open(['url' => route('urls.store'), 'method' => 'post', 'class' => 'd-flex justify-content-center flex-column flex-md-row'])}}
                        {{Form::text('url[name]', $value = "", ['class' => 'form-control form-control-lg d-block d-md-block mb-3 mb-md-0', 'placeholder' => 'https://www.example.com'])}}
                        {{Form::submit('Проверить', ['class' => 'btn btn-lg btn-primary ms-md-3 px-5 text-uppercase'])}}
                    {{Form::close()}}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/urls/index.blade.php
@extends('layouts.app')

@section('title', 'Сайты')

@section('content')
    <div class="container-lg">
        <h1 class="mt-5 mb-3">Сайты</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа</th>
                    </tr>
                    @foreach ($urls as $url)
                    <tr>
                        <td>{{$url->id}}</td>
                        <td>
                            <a href="{{route('urls.show', $url->id)}}">{{$url->name}}</a>
                        </td>
                        <td>{{$url->updated_at}}</td>
                        <td>
                            {{$lastCheck[$url->id]->status_code ?? 'Проверок еще не было'}}
                        </td>

                    </tr>
                    @endforeach

                    
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/urls/show.blade.php
@extends('layouts.app')

@section('title', 'Сайт')

@section('content')
    <div class="container-lg">
        <h2>Сайт: {{$url->name}}</h2>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td>{{$url->id}}</td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td>{{$url->name}}</td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td>{{$url->created_at}}</td>
                    </tr>
                    <tr>
                        <td>Дата обновления</td>
                        <td>{{$url->updated_at}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h3>Проверки</h3>
        {{Form::open(['url' => route('urls.checks.store', $url->id), 'method' => 'post'])}}
            {{Form::submit('Запустить проверку', ['class' => 'btn btn-primary'])}}
        {{Form::close()}}
        <br>
        <br>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap">
                <tbody>
                    <tr>
                        <th>ID</th>				
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>keywords</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                    @foreach ($cheks as $chek)
                    <tr>
                        <td>{{$chek->id}}</td>
                        <td>{{$chek->status_code}}</td>
                        <td>{{Str::limit($chek->h1, 20)}}</td>
                        <td>{{Str::limit($chek->keywords, 30)}}</td>
                        <td>{{Str::limit($chek->description, 30)}}</td>
                        <td>{{$chek->updated_at}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection